"""Run the full MILK10k exploratory data analysis end to end.

Writes every figure to ``reports/figures/``, every summary table to
``reports/tables/`` and a text digest to ``reports/eda_summary.md``.

Usage:
    python scripts/run_eda.py [--sample-size 400]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")  # headless: we are writing files, not opening windows

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

import pandas as pd  # noqa: E402

from milk10k import config, data, plots  # noqa: E402


def main(sample_size: int = 400) -> None:
    config.apply_style()
    config.ensure_dirs()

    if not config.METADATA_CSV.exists():
        raise SystemExit(
            f"Dataset not found at {config.DATA_DIR}.\n"
            "Run `bash scripts/download_data.sh` first."
        )

    # --- Load ---------------------------------------------------------------
    meta = data.load_metadata()
    gt = data.load_training_gt()
    inp = data.load_training_input()
    supp = data.load_training_supp()

    df = data.build_image_level(meta, gt, inp)
    lesion = data.build_lesion_level(df)

    lines: list[str] = []

    def log(text: str = "") -> None:
        print(text)
        lines.append(text)

    log("# MILK10k — EDA summary")
    log()
    log("_Generated by `scripts/run_eda.py`. All numbers computed from the real dataset._")
    log()

    # --- 1. Shape -----------------------------------------------------------
    log("## 1. Dataset shape")
    log()
    log("| Table | Rows | Columns | Row unit |")
    log("|---|---|---|---|")
    log(f"| metadata.csv | {len(meta):,} | {meta.shape[1]} | one image |")
    log(f"| supplements/training_gt.csv | {len(gt):,} | {gt.shape[1]} | one lesion |")
    log(f"| supplements/training_input.csv | {len(inp):,} | {inp.shape[1]} | one image |")
    log(f"| supplements/training_supp.csv | {len(supp):,} | {supp.shape[1]} | one image |")
    log(f"| images/ | {len(list(config.IMG_DIR.glob('*.jpg'))):,} | — | one JPEG |")
    log()
    log(
        f"- **{df['isic_id'].nunique():,} images** covering "
        f"**{df['lesion_id'].nunique():,} lesions** "
        f"({len(df) / df['lesion_id'].nunique():.0f} images per lesion)."
    )
    log()

    # --- 2. Integrity checks ------------------------------------------------
    checks = data.check_lesion_consistency(df)
    checks.to_csv(config.TABLES_DIR / "integrity_checks.csv", index=False)
    log("## 2. Structural integrity checks")
    log()
    log("| Check | Result | Detail |")
    log("|---|---|---|")
    for _, row in checks.iterrows():
        mark = "PASS" if row["passed"] else "FAIL"
        log(f"| {row['check']} | {mark} | {row['detail']} |")
    log()

    labels = data.gt_to_label(gt)
    multi = int((labels["n_positive"] != 1).sum())
    log(
        f"- The 11-class ground truth is genuinely single-label: "
        f"{multi} of {len(labels):,} lesions have anything other than exactly one "
        f"positive class."
    )
    log()

    # --- 3. Class distribution ---------------------------------------------
    log("## 3. Class distribution")
    log()
    primary = lesion["diagnosis_1"].value_counts()
    log("### Primary target — diagnosis_1 (lesion level)")
    log()
    log("| Class | Lesions | Share |")
    log("|---|---|---|")
    for name, count in primary.items():
        log(f"| {name} | {count:,} | {count / primary.sum():.1%} |")
    log(
        f"\n- Imbalance ratio (largest : smallest) = "
        f"**{primary.max() / primary.min():.1f} : 1**."
    )
    log(
        f"- A model that predicts *Malignant* for everything scores "
        f"**{primary.max() / primary.sum():.1%} accuracy** while catching zero benign "
        f"lesions — this is why accuracy is the wrong headline metric here."
    )
    log()

    eleven = lesion["label_11"].value_counts()
    log("### Stretch target — 11-class scheme (lesion level)")
    log()
    log("| Code | Diagnosis | Lesions | Share |")
    log("|---|---|---|---|")
    for code, count in eleven.items():
        log(
            f"| {code} | {config.DIAGNOSIS_CODES.get(code, '?')} | {count:,} | "
            f"{count / eleven.sum():.1%} |"
        )
    log(
        f"\n- Imbalance ratio = **{eleven.max() / eleven.min():.0f} : 1** "
        f"({eleven.idxmax()} = {eleven.max():,} vs {eleven.idxmin()} = {eleven.min():,})."
    )
    log()
    # How the two label schemes relate — nested, but not perfectly.
    hierarchy = data.check_label_hierarchy(lesion)
    hierarchy.to_csv(config.TABLES_DIR / "label_hierarchy.csv")
    ambiguous = data.ambiguous_codes(lesion)
    log("### How the two schemes relate")
    log()
    log("| Code | " + " | ".join(hierarchy.columns) + " |")
    log("|---" * (len(hierarchy.columns) + 1) + "|")
    for code, row in hierarchy.iterrows():
        log(f"| {code} | " + " | ".join(f"{v:,}" for v in row.values) + " |")
    if ambiguous:
        log(
            f"\n- The schemes are nested but **not** cleanly: "
            f"{', '.join(ambiguous)} maps to more than one value of `diagnosis_1`. "
            f"AKIEC in particular splits into "
            f"{hierarchy.loc['AKIEC', 'Indeterminate']:,} Indeterminate and "
            f"{hierarchy.loc['AKIEC', 'Malignant']:,} Malignant lesions — clinically "
            f"reasonable (actinic keratosis vs. intraepithelial carcinoma sit on a "
            f"continuum), but it means you cannot derive `diagnosis_1` from the "
            f"11-class code by a lookup table."
        )
    else:
        log("\n- Every 11-class code maps to exactly one value of `diagnosis_1`.")
    log()

    primary.to_frame("lesions").to_csv(config.TABLES_DIR / "class_distribution_primary.csv")
    eleven.to_frame("lesions").to_csv(config.TABLES_DIR / "class_distribution_11.csv")

    plots.plot_primary_class_distribution(lesion, "fig01_class_distribution_primary.png")
    plots.plot_11_class_distribution(lesion, "fig02_class_distribution_11.png")
    plots.plot_diagnosis_hierarchy(lesion, "fig03_diagnosis_hierarchy.png")

    # --- 4. Missing values --------------------------------------------------
    missing = df.isna().mean().sort_values(ascending=False)
    missing = missing[missing > 0]
    missing.to_frame("missing_share").to_csv(config.TABLES_DIR / "missing_values.csv")
    log("## 4. Missing values (image level)")
    log()
    log("| Column | Missing |")
    log("|---|---|")
    for name, share in missing.items():
        log(f"| {name} | {share:.1%} |")
    log()
    plots.plot_missing_values(df, "fig04_missing_values.png")

    # --- 5. Demographics ----------------------------------------------------
    log("## 5. Demographics and acquisition (lesion level)")
    log()
    age = lesion["age_approx"]
    log(
        f"- **Age**: mean {age.mean():.1f}, median {age.median():.0f}, "
        f"range {age.min():.0f}-{age.max():.0f} years "
        f"({age.isna().sum()} missing)."
    )
    sex = lesion["sex"].value_counts()
    log(
        "- **Sex**: "
        + ", ".join(f"{k} {v:,} ({v / sex.sum():.1%})" for k, v in sex.items())
        + "."
    )
    site = lesion["anatom_site_general"].fillna("(missing)").value_counts()
    log(
        "- **Anatomic site**: "
        + ", ".join(f"{k} {v:,}" for k, v in site.items())
        + "."
    )
    confirm = lesion["diagnosis_confirm_type"].value_counts()
    log(
        "- **Diagnosis confirmation**: "
        + ", ".join(f"{k} {v:,} ({v / confirm.sum():.1%})" for k, v in confirm.items())
        + "."
    )
    log()
    plots.plot_demographics(lesion, "fig05_demographics.png")
    plots.plot_anatomic_site(lesion, "fig06_anatomic_site.png")

    # --- 6. Skin tone -------------------------------------------------------
    tone = lesion["skin_tone_class"].value_counts().sort_index()
    tone.to_frame("lesions").to_csv(config.TABLES_DIR / "skin_tone_distribution.csv")
    log("## 6. Skin tone — the fairness slice")
    log()
    log("| Skin tone class | Lesions | Share |")
    log("|---|---|---|")
    for value, count in tone.items():
        log(
            f"| {config.SKIN_TONE_LABELS.get(int(value), value)} | {count:,} | "
            f"{count / tone.sum():.1%} |"
        )
    top = tone.idxmax()
    log(
        f"\n- Class {config.SKIN_TONE_LABELS.get(int(top), top)} alone accounts for "
        f"{tone.max() / tone.sum():.1%} of lesions. The darkest and lightest tones are "
        f"barely represented, so per-group evaluation is mandatory before any claim "
        f"about real-world performance."
    )
    log()
    plots.plot_skin_tone(lesion, "fig07_skin_tone.png")

    # --- 7. Image properties ------------------------------------------------
    log(f"## 7. Image properties (random sample of {sample_size} JPEGs)")
    log()
    stats = data.sample_image_stats(df, n=sample_size, seed=0)
    stats.to_csv(config.TABLES_DIR / "image_sample_stats.csv", index=False)

    log("| Image type | n | Mean width | Mean height | Mean MP | Mean size (KB) |")
    log("|---|---|---|---|---|---|")
    for t, g in stats.groupby("image_type"):
        log(
            f"| {t} | {len(g)} | {g['width'].mean():.0f} | {g['height'].mean():.0f} | "
            f"{g['megapixels'].mean():.2f} | {g['file_size_kb'].mean():.0f} |"
        )
    log(
        f"\n- Overall mean size: **{stats['width'].mean():.0f} x "
        f"{stats['height'].mean():.0f} px**; "
        f"{stats['width'].min():.0f}-{stats['width'].max():.0f} px wide across the sample."
    )
    log(
        f"- Distinct resolutions in the sample: "
        f"{stats.groupby(['width', 'height']).ngroups} — images are **not** uniform, "
        f"so a resize step is required before batching."
    )
    log(
        "- Mean channel intensity by type: "
        + "; ".join(
            f"{t}: R {g['mean_r'].mean():.0f} / G {g['mean_g'].mean():.0f} / "
            f"B {g['mean_b'].mean():.0f}"
            for t, g in stats.groupby("image_type")
        )
        + "."
    )
    log()
    plots.plot_image_properties(stats, "fig08_image_properties.png")
    plots.plot_color_statistics(stats, "fig09_color_statistics.png")

    # --- 8. Visual inspection ----------------------------------------------
    plots.plot_class_gallery(df, save_as="fig10_class_gallery.png")
    plots.plot_lesion_pairs(df, n_lesions=3, save_as="fig11_lesion_pairs.png")
    plots.show_samples(df, n=6, diagnosis="Malignant", save_as="fig12_samples_malignant.png")
    plots.show_samples(df, n=6, diagnosis="Benign", save_as="fig13_samples_benign.png")

    # --- 9. MONET concepts --------------------------------------------------
    monet_cols = [c for c in df.columns if c.startswith("MONET_")]
    log("## 8. MONET semantic-concept scores")
    log()
    log(f"- {len(monet_cols)} per-image concept scores are supplied: "
        + ", ".join(c.replace("MONET_", "") for c in monet_cols)
        + ".")
    derm = df[df["image_type"] == "dermoscopic"]
    clin = df[df["image_type"] == "clinical: close-up"]
    log()
    log("| Concept | Mean (dermoscopic) | Mean (clinical) |")
    log("|---|---|---|")
    for col in monet_cols:
        log(
            f"| {col.replace('MONET_', '')} | {derm[col].mean():.3f} | "
            f"{clin[col].mean():.3f} |"
        )
    log()
    plots.plot_monet_by_image_type(df, "fig14_monet_by_image_type.png")
    plots.plot_monet_by_class(df, "fig15_monet_by_class.png")

    # --- 10. Takeaways ------------------------------------------------------
    log("## 9. What this means for the modelling pipeline")
    log()
    log(
        f"1. **Split on `lesion_id`, never on image rows.** Every lesion has exactly two "
        f"images of the same skin. A random row split leaks {df['lesion_id'].nunique():,} "
        f"lesions across train and test and inflates every score."
    )
    log(
        f"2. **Do not report plain accuracy.** With {primary.max() / primary.sum():.1%} of "
        f"lesions in one class, a constant prediction beats most honest models on accuracy. "
        f"Use balanced accuracy, macro-F1, per-class recall and, above all, "
        f"**sensitivity on malignant lesions**."
    )
    log(
        f"3. **The 11-class target is severely imbalanced "
        f"({eleven.max() / eleven.min():.0f}:1).** Classes such as "
        f"{', '.join(eleven.tail(3).index)} have only "
        f"{', '.join(str(v) for v in eleven.tail(3).values)} lesions — expect to need "
        f"class weighting, oversampling or merged categories."
    )
    log(
        "4. **Two modalities, two pixel distributions.** Dermoscopic and clinical images "
        "differ measurably in colour and contrast. Treat `image_type` as a first-class "
        "feature: train separate heads, condition on it, or at minimum stratify by it."
    )
    log(
        f"5. **Metadata is not free.** `anatom_site_general` is missing for "
        f"{df['anatom_site_general'].isna().mean():.0%} of images and `melanocytic` for "
        f"{df['melanocytic'].isna().mean():.0%}. Any metadata feature needs an explicit "
        f"missing-value strategy."
    )
    log(
        f"6. **Report fairness by skin tone.** Skin tone class "
        f"{config.SKIN_TONE_LABELS.get(int(top), top)} is "
        f"{tone.max() / tone.sum():.0%} of the data; the extremes are almost absent. "
        f"Aggregate metrics will hide failures on under-sampled groups."
    )
    log()

    summary_path = config.REPORTS_DIR / "eda_summary.md"
    summary_path.write_text("\n".join(lines) + "\n")

    n_figs = len(list(config.FIGURES_DIR.glob("*.png")))
    print(f"\nWrote {n_figs} figures to {config.FIGURES_DIR}")
    print(f"Wrote summary to {summary_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--sample-size",
        type=int,
        default=400,
        help="How many JPEGs to open when measuring image properties.",
    )
    args = parser.parse_args()
    main(sample_size=args.sample_size)
